export const HomePage = () => {
  return (
    <div>
      <h1>HomePage</h1>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
      <h2>Post</h2>
    </div>
  )
}
